if(NOT DEFINED PROGRAM OR NOT DEFINED EXPECT_EXIT)
  message(FATAL_ERROR "CLI test requires PROGRAM and EXPECT_EXIT")
endif()
execute_process(COMMAND ${EMULATOR} "${PROGRAM}" ${ARGUMENTS}
  RESULT_VARIABLE actual OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 20)
set(combined "${out}${err}")
if(NOT "${actual}" STREQUAL "${EXPECT_EXIT}")
  message(FATAL_ERROR "Expected exit ${EXPECT_EXIT}, got ${actual}\n${combined}")
endif()
if(NOT combined MATCHES "${EXPECT_TEXT}")
  message(FATAL_ERROR "Missing expected text '${EXPECT_TEXT}'\n${combined}")
endif()
if(NOT "${FORBID_TEXT}" STREQUAL "" AND combined MATCHES "${FORBID_TEXT}")
  message(FATAL_ERROR "Forbidden text '${FORBID_TEXT}'\n${combined}")
endif()
message(STATUS "Expected exit ${actual} verified\n${combined}")