file(GLOB_RECURSE headers "${ROOT}/core/include/*.hpp" "${ROOT}/window/include/*.hpp" "${ROOT}/graphics/include/*.hpp" "${ROOT}/gx2/include/*.hpp")
if(NOT headers)
  message(FATAL_ERROR "No public headers found")
endif()
foreach(header IN LISTS headers)
  file(READ "${header}" text)
  if(text MATCHES "SDL_[A-Za-z]|Vk[A-Z][A-Za-z]|ID3D12|D3D12_|GLFW[A-Za-z]|GLenum|GLuint|GLsync|vulkan/|windows\\.h|SDL3/")
    message(FATAL_ERROR "Native graphics/window token leaked into ${header}")
  endif()
endforeach()
message(STATUS "Public API native-type guard passed (lexical guard, not an ABI proof)")