if(PLATFORM STREQUAL "windows-x64")
  set(exe_suffix ".exe")
elseif(PLATFORM MATCHES "^linux-(x64|arm64)$")
  set(exe_suffix "")
else()
  message(FATAL_ERROR "Unsupported artifact platform: ${PLATFORM}")
endif()
set(artifacts "libmanmenmi_core.a" "manmenmi_probe${exe_suffix}")
foreach(suite IN ITEMS core config log contracts)
  list(APPEND artifacts "tests/manmenmi_${suite}_tests${exe_suffix}")
endforeach()