cmake_minimum_required(VERSION 3.25)
if(NOT PLATFORM MATCHES "^(linux-x64|windows-x64)$" OR NOT DEFINED DEST)
  message(FATAL_ERROR "Pass PLATFORM=linux-x64|windows-x64 and DEST outside the source tree")
endif()
if(NOT DEFINED LOCK_FILE)
  set(LOCK_FILE "${CMAKE_CURRENT_LIST_DIR}/toolchain-lock.json")
endif()
if(NOT DEFINED DOWNLOAD_DIR)
  set(DOWNLOAD_DIR "${DEST}/downloads")
endif()
cmake_host_system_information(RESULT host_arch QUERY OS_PLATFORM)
if(NOT VERIFY_ONLY)
  if(NOT host_arch MATCHES "^(x86_64|AMD64|amd64)$" OR
      (PLATFORM STREQUAL "linux-x64" AND NOT CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux") OR
      (PLATFORM STREQUAL "windows-x64" AND NOT CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows"))
    message(FATAL_ERROR "Native x64 host required; VERIFY_ONLY checks archives without executing/installing tools")
  endif()
endif()
file(READ "${LOCK_FILE}" lock)
string(JSON schema GET "${lock}" schema_version)
if(NOT schema EQUAL 1)
  message(FATAL_ERROR "Unsupported toolchain lock schema")
endif()
file(MAKE_DIRECTORY "${DEST}" "${DOWNLOAD_DIR}")
file(SHA256 "${LOCK_FILE}" lock_hash)
file(WRITE "${DEST}/bootstrap-evidence.txt" "lock_sha256=${lock_hash}\nplatform=${PLATFORM}\nhost=${CMAKE_HOST_SYSTEM_NAME}/${host_arch}\nverify_only=${VERIFY_ONLY}\n")
string(JSON count LENGTH "${lock}" archives)
math(EXPR last "${count}-1")
foreach(i RANGE 0 ${last})
  string(JSON item GET "${lock}" archives ${i})
  string(JSON item_platform GET "${item}" platform)
  if(NOT item_platform STREQUAL PLATFORM)
    continue()
  endif()
  foreach(field IN ITEMS id url sha256 file kind bin version)
    string(JSON ${field} GET "${item}" ${field})
  endforeach()
  string(LENGTH "${sha256}" hash_length)
  if(NOT hash_length EQUAL 64 OR NOT sha256 MATCHES "^[0-9a-f]+$" OR NOT url MATCHES "^https://")
    message(FATAL_ERROR "Invalid locked digest/URL for ${id}")
  endif()
  set(archive "${DOWNLOAD_DIR}/${file}")
  if(NOT EXISTS "${archive}")
    file(DOWNLOAD "${url}" "${archive}" EXPECTED_HASH "SHA256=${sha256}" TLS_VERIFY ON
      TIMEOUT 1200 INACTIVITY_TIMEOUT 90 STATUS download_status)
    list(GET download_status 0 code)
    if(NOT code EQUAL 0)
      message(FATAL_ERROR "Download failed for ${id}: ${download_status}")
    endif()
  endif()
  # Cached bytes are not trusted either. Do not silently replace a mismatched archive.
  file(SHA256 "${archive}" actual)
  if(NOT actual STREQUAL sha256)
    message(FATAL_ERROR "SHA256_MISMATCH ${id}: expected ${sha256}, got ${actual}; nothing extracted")
  endif()
  file(APPEND "${DEST}/bootstrap-evidence.txt" "VERIFIED ${id} ${version} SHA256=${actual}\n")
  if(VERIFY_ONLY)
    continue()
  endif()
  set(install "${DEST}/${id}")
  file(MAKE_DIRECTORY "${install}")
  if(kind STREQUAL "archive")
    file(ARCHIVE_EXTRACT INPUT "${archive}" DESTINATION "${install}")
    list(APPEND paths "${install}/${bin}")
  elseif(kind STREQUAL "deb" AND PLATFORM STREQUAL "linux-x64")
    find_program(DPKG_DEB dpkg-deb REQUIRED)
    execute_process(COMMAND "${DPKG_DEB}" -x "${archive}" "${install}" COMMAND_ERROR_IS_FATAL ANY)
    set(library_path "${install}/${bin}")
  else()
    message(FATAL_ERROR "Unsupported archive kind: ${kind}")
  endif()
  if(NOT IS_DIRECTORY "${install}/${bin}")
    message(FATAL_ERROR "Unexpected archive layout: ${id}/${bin}")
  endif()
endforeach()
if(NOT VERIFY_ONLY)
  if(DEFINED ENV{GITHUB_PATH})
    foreach(path IN LISTS paths)
      file(APPEND "$ENV{GITHUB_PATH}" "${path}\n")
    endforeach()
  endif()
  if(DEFINED library_path AND DEFINED ENV{GITHUB_ENV})
    file(APPEND "$ENV{GITHUB_ENV}" "LD_LIBRARY_PATH=${library_path}\n")
  endif()
  file(WRITE "${DEST}/tools-env.cmake" "set(M0_TOOL_PATHS \"${paths}\")\nset(M0_LIBRARY_PATH \"${library_path}\")\n")
endif()
message(STATUS "Locked archives verified for ${PLATFORM}; VERIFY_ONLY=${VERIFY_ONLY}")