cmake_minimum_required(VERSION 3.25)
if(NOT DEFINED PRESET OR NOT DEFINED PLATFORM OR NOT DEFINED TOOLS_DIR)
  message(FATAL_ERROR "PRESET, PLATFORM and TOOLS_DIR are required")
endif()
get_filename_component(root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(build "${root}/build/${PRESET}")
file(MAKE_DIRECTORY "${build}")
file(COPY "${TOOLS_DIR}/bootstrap-evidence.txt" "${CMAKE_CURRENT_LIST_DIR}/toolchain-lock.json" DESTINATION "${build}")
function(stage name)
  execute_process(COMMAND ${ARGN} WORKING_DIRECTORY "${root}"
    RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err)
  file(WRITE "${build}/${name}.log" "${out}\n${err}\nexit=${result}\n")
  message(STATUS "${name}:\n${out}\n${err}")
  if(NOT "${result}" STREQUAL "0")
    message(FATAL_ERROR "CI stage ${name} failed with ${result}")
  endif()
endfunction()
stage(tool-versions "${CMAKE_COMMAND}" "-DDEST=${build}" "-DPLATFORM=${PLATFORM}" -P "${CMAKE_CURRENT_LIST_DIR}/VerifyTools.cmake")
stage(repository "${CMAKE_COMMAND}" "-DROOT=${root}" "-DDEST=${build}" -P "${CMAKE_CURRENT_LIST_DIR}/CheckRepository.cmake")
stage(failure-propagation "${CMAKE_COMMAND}" "-DDEST=${build}/negative-control" -P "${CMAKE_CURRENT_LIST_DIR}/CheckFailurePropagation.cmake")
stage(configure "${CMAKE_COMMAND}" --preset "${PRESET}" "-DMANMENMI_CI_INJECT_FAILURE=${INJECT_FAILURE}")
stage(build "${CMAKE_COMMAND}" --build --preset "${PRESET}" --parallel 2)
set(expected 26)
if(INJECT_FAILURE)
  set(expected 27)
endif()
stage(tests "${CMAKE_COMMAND}" "-DBUILD_DIR=${build}" "-DEXPECTED_TESTS=${expected}" -P "${CMAKE_CURRENT_LIST_DIR}/RunTests.cmake")
stage(artifacts "${CMAKE_COMMAND}" "-DBUILD_DIR=${build}" "-DPLATFORM=${PLATFORM}" -P "${CMAKE_CURRENT_LIST_DIR}/VerifyArtifacts.cmake")
if(PRESET MATCHES "-coverage$")
  stage(coverage "${CMAKE_COMMAND}" "-DBUILD_DIR=${build}" -P "${root}/cmake/Coverage.cmake")
elseif(PRESET MATCHES "-(debug|release)$")
  set(second "${root}/build/repro/${PRESET}")
  if(EXISTS "${second}/CMakeCache.txt")
    message(FATAL_ERROR "Reproducibility requires a fresh second build directory")
  endif()
  stage(repro-configure "${CMAKE_COMMAND}" --preset "${PRESET}" -B "${second}" -DMANMENMI_CI_INJECT_FAILURE=OFF)
  stage(repro-build "${CMAKE_COMMAND}" --build "${second}" --parallel 2)
  stage(repro-compare "${CMAKE_COMMAND}" "-DFIRST=${build}" "-DSECOND=${second}" "-DPLATFORM=${PLATFORM}" -P "${CMAKE_CURRENT_LIST_DIR}/CheckReproducibility.cmake")
endif()
message(STATUS "Job checks PASS. Closing M0 still requires all native run references and independent evidence review.")