cmake_minimum_required(VERSION 3.25)
if(NOT DEFINED FIRST OR NOT DEFINED SECOND OR NOT DEFINED PLATFORM)
  message(FATAL_ERROR "Pass FIRST, SECOND and PLATFORM")
endif()
file(REAL_PATH "${FIRST}" first_real)
file(REAL_PATH "${SECOND}" second_real)
if(first_real STREQUAL second_real)
  message(FATAL_ERROR "Reproducibility needs two separate clean build directories")
endif()
include("${CMAKE_CURRENT_LIST_DIR}/ArtifactList.cmake")
file(WRITE "${FIRST}/reproducibility.txt" "Scope: two clean builds, same sources/toolchain/environment/configuration, separate directories.\nPlatform=${PLATFORM}\n")
foreach(relative IN LISTS artifacts)
  file(SHA256 "${FIRST}/${relative}" a)
  file(SHA256 "${SECOND}/${relative}" b)
  if(NOT a STREQUAL b)
    file(APPEND "${FIRST}/reproducibility.txt" "FAIL ${relative} ${a} != ${b}\n")
    message(FATAL_ERROR "NON_REPRODUCIBLE artifact: ${relative}")
  endif()
  file(APPEND "${FIRST}/reproducibility.txt" "VERIFIED ${relative} ${a}\n")
endforeach()
message(STATUS "VERIFIED: six byte-identical build artifacts; no cross-host/hermetic claim")