cmake_minimum_required(VERSION 3.25)
if(NOT DEFINED ROOT OR NOT DEFINED DEST)
  message(FATAL_ERROR "ROOT and DEST required")
endif()
execute_process(COMMAND git -C "${ROOT}" ls-files --cached --others --exclude-standard
  OUTPUT_VARIABLE listing COMMAND_ERROR_IS_FATAL ANY)
string(REPLACE "\n" ";" paths "${listing}")
list(REMOVE_DUPLICATES paths)
file(MAKE_DIRECTORY "${DEST}")
file(WRITE "${DEST}/source-manifest.sha256" "")
foreach(path IN LISTS paths)
  if(path STREQUAL "")
    continue()
  endif()
  string(TOLOWER "${path}" lower)
  if(lower MATCHES "[.](rpx|rpl|wud|wux|iso|wad|tik|tmd|key|exe|dll|so|a|o|obj|zip|7z|deb|profraw|profdata)$" OR
      lower MATCHES "(^|/)(dumps|node_modules|frontend|backend)/|(^|/)[.]env($|[.])")
    message(FATAL_ERROR "Forbidden source repository path: ${path}")
  endif()
  # Tracked deletions are not part of the proposed source snapshot.
  if(NOT EXISTS "${ROOT}/${path}")
    continue()
  endif()
  file(READ "${ROOT}/${path}" magic LIMIT 4 HEX)
  if(magic MATCHES "^(7f454c46|4d5a|52504c00|57554400)")
    message(FATAL_ERROR "Unexpected binary in source snapshot: ${path}")
  endif()
  file(SHA256 "${ROOT}/${path}" sha)
  file(APPEND "${DEST}/source-manifest.sha256" "${sha}  ${path}\n")
endforeach()
file(READ "${ROOT}/LICENSE" license)
if(NOT license MATCHES "MIT License" OR NOT license MATCHES "Permission is hereby granted, free of charge")
  message(FATAL_ERROR "Original-code MIT license missing/inconsistent")
endif()
file(READ "${ROOT}/CMakeLists.txt" build)
if(build MATCHES "FetchContent|ExternalProject|find_package\\((SDL|Vulkan|GX2|Cafe)|add_subdirectory\\((gx2|cafe|backends)")
  message(FATAL_ERROR "M0 dependency boundary changed; review required")
endif()
file(WRITE "${DEST}/repository-check.txt" "PASS: proposed Git source paths, binary signatures, MIT and M0 CMake boundary checks.\nScope: bounded hygiene check; not a legal certification or comprehensive secret audit.\nIgnored local data is not inventoried or uploaded.\n")
message(STATUS "M0 bounded repository hygiene checks PASS")