cmake_minimum_required(VERSION 3.25)
if(NOT DEFINED BUILD_DIR OR NOT DEFINED PLATFORM)
  message(FATAL_ERROR "BUILD_DIR and PLATFORM are required")
endif()
include("${CMAKE_CURRENT_LIST_DIR}/ArtifactList.cmake")
if(CHECK_MANIFEST)
  file(READ "${BUILD_DIR}/artifact-manifest.sha256" expected_manifest)
endif()
set(manifest "")
foreach(relative IN LISTS artifacts)
  set(path "${BUILD_DIR}/${relative}")
  if(NOT EXISTS "${path}" OR IS_DIRECTORY "${path}")
    message(FATAL_ERROR "Missing build artifact: ${relative}")
  endif()
  file(SIZE "${path}" size)
  if(size LESS 64)
    message(FATAL_ERROR "Truncated artifact: ${relative}")
  endif()
  file(READ "${path}" header LIMIT 20 HEX)
  if(relative MATCHES "[.]a$")
    if(NOT header MATCHES "^213c617263683e0a")
      message(FATAL_ERROR "Not a static archive: ${relative}")
    endif()
  elseif(PLATFORM STREQUAL "windows-x64")
    if(NOT header MATCHES "^4d5a")
      message(FATAL_ERROR "Not a PE image: ${relative}")
    endif()
    file(READ "${path}" address OFFSET 60 LIMIT 4 HEX)
    string(SUBSTRING "${address}" 0 2 a)
    string(SUBSTRING "${address}" 2 2 b)
    string(SUBSTRING "${address}" 4 2 c)
    string(SUBSTRING "${address}" 6 2 d)
    math(EXPR pe_offset "0x${d}${c}${b}${a}")
    file(READ "${path}" pe OFFSET ${pe_offset} LIMIT 6 HEX)
    if(NOT pe STREQUAL "504500006486")
      message(FATAL_ERROR "PE artifact is not AMD64: ${relative}")
    endif()
  else()
    string(SUBSTRING "${header}" 36 4 machine)
    if(NOT header MATCHES "^7f454c460201" OR
        (PLATFORM STREQUAL "linux-x64" AND NOT machine STREQUAL "3e00") OR
        (PLATFORM STREQUAL "linux-arm64" AND NOT machine STREQUAL "b700"))
      message(FATAL_ERROR "Wrong ELF architecture: ${relative}")
    endif()
  endif()
  file(SHA256 "${path}" digest)
  string(APPEND manifest "${digest}  ${relative}\n")
endforeach()
if(NOT BUILD_ONLY)
  file(READ "${BUILD_DIR}/results.xml" junit)
  string(REGEX MATCHALL "<testcase " cases "${junit}")
  list(LENGTH cases case_count)
  if(NOT case_count EQUAL 26 OR NOT junit MATCHES "tests=\"26\"" OR
      NOT junit MATCHES "failures=\"0\"" OR NOT junit MATCHES "skipped=\"0\"" OR
      junit MATCHES "<failure[ >]|<skipped[ />]")
    message(FATAL_ERROR "Artifacts require 26 passing, zero-skipped M0 tests")
  endif()
endif()
if(CHECK_MANIFEST)
  if(NOT manifest STREQUAL expected_manifest)
    message(FATAL_ERROR "Artifact SHA256 manifest mismatch")
  endif()
else()
  file(WRITE "${BUILD_DIR}/artifact-manifest.sha256" "${manifest}")
endif()
message(STATUS "Artifacts verified: ${PLATFORM}; BUILD_ONLY=${BUILD_ONLY}; not a native runtime claim")