cmake_minimum_required(VERSION 3.25)
if(NOT DEFINED DEST OR NOT PLATFORM MATCHES "^(linux-x64|windows-x64)$")
  message(FATAL_ERROR "DEST and PLATFORM are required")
endif()
if(NOT CMAKE_VERSION VERSION_EQUAL "3.31.6")
  message(FATAL_ERROR "CI build must use locked CMake 3.31.6, got ${CMAKE_VERSION}")
endif()
cmake_host_system_information(RESULT arch QUERY OS_PLATFORM)
if(NOT arch MATCHES "^(x86_64|AMD64|amd64)$")
  message(FATAL_ERROR "Native x64 required for CI evidence")
endif()
if(PLATFORM STREQUAL "windows-x64")
  set(compiler_name x86_64-w64-mingw32-clang++)
else()
  set(compiler_name clang++)
endif()
find_program(compiler NAMES "${compiler_name}" REQUIRED)
find_program(ninja NAMES ninja REQUIRED)
execute_process(COMMAND "${compiler}" --version OUTPUT_VARIABLE compiler_info COMMAND_ERROR_IS_FATAL ANY)
execute_process(COMMAND "${ninja}" --version OUTPUT_VARIABLE ninja_info OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
if(NOT compiler_info MATCHES "clang version 18[.]1[.]8[ \r\n]" OR NOT ninja_info STREQUAL "1.11.1")
  message(FATAL_ERROR "Unexpected compiler or Ninja version: ${compiler_info} / ${ninja_info}")
endif()
execute_process(COMMAND git rev-parse HEAD OUTPUT_VARIABLE revision OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
file(MAKE_DIRECTORY "${DEST}")
file(WRITE "${DEST}/toolchain.txt" "Platform=${PLATFORM}\nHost=${CMAKE_HOST_SYSTEM_NAME}/${arch}\nCompiler=${compiler}\n${compiler_info}\nCMake=${CMAKE_VERSION}\nNinja=${ninja_info}\nCommit=${revision}\nImageOS=$ENV{ImageOS}\nImageVersion=$ENV{ImageVersion}\nCI_run=$ENV{GITHUB_RUN_ID}\nCI_attempt=$ENV{GITHUB_RUN_ATTEMPT}\n")
if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
  execute_process(COMMAND dpkg-query -W OUTPUT_FILE "${DEST}/system-packages.txt" COMMAND_ERROR_IS_FATAL ANY)
endif()
message(STATUS "CI tool versions verified; native execution results must still come from CTest")